config/routes.rb
MyAssignment::Application.routes.draw do
  get "sessions/new"

  get "session/new"

  resources :book_categories

  get "store/index"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    post "logout" => :destroy
  end

  resources :carts

  resources :order_lines

  resources :orders

  resources :comments

  resources :categories

  resources :users
  devise_scope :user do
    controller "my_devise/my_passwords" do
      get "reset_password/reset_password_token/:reset_password_token", :to => :reset_password, :as => 'reset_password' 
      post "update_password", :to => :update_password
    end
  end
  devise_for :users, :controllers => {:passwords => "my_devise/my_passwords" }
  controller :users do 
    get "my_profile", :to => :edit_profile
    get "change_password", :to => :change_password
    get "change_email", :to => :change_email
  end

  controller :orders do 
    get "my_orders", :to => :my_orders
  end
  controller :carts do 
    get "check_session_alive", :to => :check_session_alive
  end

  
  get "category/:category/per/:per", :to => "store#index", :as => 'category_filter'
  post "order_lines/book/:book_id", :to => "order_lines#create", :as => 'add_to_cart'
  match "store/index?page=:id", :to => 'store#index', :as => 'store'
  get "store/per/:per", :to => 'store#index'

  root to: 'store#index', as: 'store' 
  resources :books

  match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :encrypt_password

  attr_accessible :email, :birthday, :create_date, :full_name, :password, :hash_password, :phone, 
  	:username, :password_confirmation, :admin, :confirmation_token, :confirmed_at, :fail_attempts
  attr_accessor :password

  has_many :orders, dependent: :destroy
  has_many :comments

  EMAIL_REGULAR_EXP = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  PHONE_EXP = /^[0-9]+$/i
  validates :username, :presence => true, :uniqueness => true
  validates :full_name, :presence => true
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGULAR_EXP
  validates :password, :confirmation => true
  validates :phone, :presence => true, :format => PHONE_EXP

  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :stretches => 20
  
  class << self
    def authenticate(username,password)
      user=find_by_username(username)
      return nil unless user 
      typed_hashed_password = BCrypt::Engine.hash_secret(password,user.salt)
      if user && user.hash_password == typed_hashed_password
        user
      elsif user && user.hash_password != typed_hashed_password
        user.fail_attempts -= 1
        user.save
        nil
      else
        nil
      end
    end

    def confirm_user(confirm_token)
      user = find_by_confirmation_token(confirm_token)
      if user 
        user.update_attributes(:confirmed_at => DateTime.now)
        return user
      else
        return nil
      end 
    end

    def update_password(reset_params)
      if reset_params[:password].empty? || reset_params[:password_confirmation].empty?
        return "Alert: some fields are missing"
      elsif reset_params[:password] != reset_params[:password_confirmation]
        return "Alert: Password and Password Confirm mismatch"
      else
        user = User.find_by_reset_password_token(reset_params[:reset_password_token])
        user.update_attributes(:password => reset_params[:password])
        return "Your password is updated"
      end
    end
  end

  def is_activated
    return true if confirmed_at != nil
    return false
  end

  def encrypt_password 
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.hash_password = BCrypt::Engine.hash_secret(password,self.salt)
    end
  end

  def clear_password
  	self.password = nil
  end

  def update_password(password_params)    
    if password_params[:old].empty? || password_params[:new].empty?
      return "Alert: Some Fields are empty"
    else 
      typed_hashed_password = BCrypt::Engine.hash_secret(password_params[:old],salt)
      if typed_hashed_password != hash_password
        return "Alert: Invalid Password"
      elsif password_params[:new] != password_params[:confirm_new]
        return "Alert: New Password and confirm mismatch"
      else
        update_attributes({:password => password_params[:new] })
        return "The new password is updated"
      end    
    end   
  end

  def update_email(email_params)
    if email_params[:old].empty? 
      return "Alert: Your email is empty"
    elsif email_params[:new].empty?
      return "Alert: Your new email is empty"
    elsif !(email_params[:new] =~ EMAIL_REGULAR_EXP) 
      return "Alert: Invalid email format"
    elsif email_params[:password].empty?
      return "Alert: Your password is empty"
    else
      typed_hashed_password = BCrypt::Engine.hash_secret(email_params[:password],salt)
      if hash_password != typed_hashed_password
        return "Alert: Invalid password"
      else
        update_attributes({ :email => email_params[:new] })
        return "Your email has been updated"
      end
    end   
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  before_filter :authenticate, :except => [:create, :new, :show]
  before_filter :admin_authorize, :only => [:index, :edit, :destroy]
  def index
    @cart = current_cart
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @cart = current_cart
    @user = User.confirm_user(params[:confirmation_token])

    respond_to do |format|
      if @user
        session[:user_id] = @user.id 
        format.html { redirect_to store_url, notice: "Your account is now activated "}
        format.json { render json: @user }
      else
        format.html { redirect_to store_url, alert: "The activation code is invalid "}
        format.json { render json: @user }
      end
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @cart = current_cart
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @cart = current_cart
    @user = User.find(params[:id])    
  end

  # GET /my_profile
  def edit_profile
    @cart = current_cart
    @user = current_user
  end

  #GET /change_password
  def change_password
    @cart = current_cart
    @user = current_user
  end

  # GET /change_email
  def change_email
    @cart = current_cart
    @user = current_user
  end

  # PUT /update_password
  def update_password
    @cart = current_cart
    @user = current_user
    result = current_user.update_password(params[:update_password_info])
    respond_to do |format|
      if result.include? "Alert"
        flash[:alert] = result
        format.html { render action: "change_password"}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to store_url, :notice => result }
        format.json { head :no_content }
      end
    end
  end

  # PUT /update_email
  def update_email
    @cart = current_cart
    @user = current_user
    result = current_user.update_email(params[:update_email_info])
    respond_to do |format|
      if result.include? "Alert"
        flash[:alert] = result
        format.html { render action: "change_email"}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to store_url, :notice => result }
        format.json { head :no_content }
      end
    end
  end
  # POST /users
  # POST /users.json
  def create
    @cart = current_cart
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        flash[:notice] = "Successfully registered"
        flash[:color] = "valid"
        format.html { redirect_to store_url, notice: 'User created. The activation link has been sent' }
        format.json { render json: @user, status: :created, location: @user }
      else
        flash[:notice] = "The form is invalid"
        flash[:color] = "invalid"
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to store_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.text_field :password
  .field
    = f.label :phone
    %br/
    = f.text_field :phone
  .field
    = f.label :full_name
    %br/
    = f.text_field :full_name
  .field
    = f.label :birthday
    %br/
    = f.date_select :birthday
  .field
    = f.label :create_date
    %br/
    = f.date_select :create_date
  .actions
    = f.submit

app/views/users/change_email.html.haml
%h1 Change Email
= form_for :update_email_info, :url => { :controller => 'users', :action => 'update_email' } do |f|
  .field
    = f.label "Old email"
    %br/
    = f.text_field :old, :value => @user.email, :readonly => true
  .field
    = f.label "New email"
    %br/
    = f.text_field :new
  .field
    = f.label "Password"
    %br/
    = f.password_field :password
  .actions
    = f.submit :Change
= link_to 'Back', my_profile_path
= link_to 'Back to Store', store_path

app/views/users/change_password.html.haml
%h1 Change Password
= form_for :update_password_info, :url => { :controller => 'users', :action => 'update_password' } do |f|
  .field
    = f.label "Old Password"
    %br/
    = f.password_field :old
  .field
    = f.label "New Password"
    %br/
    = f.password_field :new
  .field
    = f.label "Confirm New Password"
    %br/
    = f.password_field :confirm_new
  .actions
    = f.submit :Change
= link_to 'Back', my_profile_path
= link_to 'Back to Store', store_path

app/views/users/edit.html.haml
%h1 Editing user
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.text_field :password
  .field
    = f.label :phone
    %br/
    = f.text_field :phone
  .field
    = f.label :full_name
    %br/
    = f.text_field :full_name
  .field
    = f.label :birthday
    %br/
    = f.date_select :birthday
  .actions
    = f.submit
= link_to 'Back', users_path

app/views/users/edit_profile.html.haml
%h1 My Profile
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  / .field
  /   = f.label :email
  /   %br/
  /   = f.text_field :email
  / .field
  /   = f.label :password
  /   %br/
  /   = f.text_field :password
  .field
    = f.label :phone
    %br/
    = f.text_field :phone
  .field
    = f.label :full_name
    %br/
    = f.text_field :full_name
  .field
    = f.label :birthday
    %br/
    = f.date_select :birthday
  .actions
    = f.submit
= link_to 'Back', store_path
= link_to 'Change Password', change_password_path
= link_to 'Change Email', change_email_path

app/views/users/index.html.haml
%h1 Listing users
%table.table.table-striped.table-condensed
  %tr
    %th email
    %th Username
    %th Phone
    %th Full name
    %th
      Admin
    %th Birthday
    %th Create date
    %th Confirmed at
    %th
    %th
    %th
  - @users.each do |user|
    %tr
      %td= user. email
      %td= user.username
      %td= user.phone
      %td= user.full_name
      %td= user.admin
      %td= user.birthday
      %td= user.create_date
      %td= user.confirmed_at
      %td= link_to 'Edit', edit_user_path(user), :class => "btn btn-warning btn-xs "
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs"
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
= form_for :user, :url => {:controller => 'users', :action => 'create'}  do |f|
  %h1 Signup Form
  .col-md-6.col-md-offset-3
    .input-group
      / Username
      %span.input-group-addon Username
      = f.text_field :username, :placeholder => "Username", :class => "form-control"
    %br/
  .col-md-6.col-md-offset-3
    .input-group
      / Email
      %span.input-group-addon Email
      = f.text_field :email, :placeholder => "Email", :class => "form-control"
    %br/
  .col-md-6.col-md-offset-3
    .input-group
      / Password
      %span.input-group-addon Password
      = f.password_field :password, :placeholder => "Password", :class => "form-control"
    %br/
  .col-md-6.col-md-offset-3
    .input-group
      / Password confirmation
      %span.input-group-addon Password Confirm
      = f.password_field :password_confirmation, :placeholder => "Password Confirmation", :class => "form-control"
    %br/
  .col-md-6.col-md-offset-3
    .input-group
      / Full Name
      %span.input-group-addon Full Name
      = f.text_field :full_name, :placeholder => "Full Name", :class => "form-control"
    %br/
  .col-md-6.col-md-offset-3
    .input-group
      / Birthday
      %span.input-group-addon Birthday
      = f.date_select :birthday, :start_year => 1970, :end_year => 2013, :class => "form-controls"
    %br/
  .col-md-6.col-md-offset-3
    .input-group
      / Phone
      %span.input-group-addon Phone
      = f.text_field :phone, :placeholder => "Phone", :class => "form-control"
    %br/
  / Button
  .col-md-7.col-md-offset-5
    = f.submit :Signup, :class => "btn btn-success"
  - if @user.errors.any?
    %ul.Signup_Errors
      - for message_error in @user.errors.full_messages
        %li
          * #{message_error}
  = f.hidden_field :create_date, :value => Time.current.to_date

app/views/users/show.html.haml
%p#notice= notice
%p
  %b email:
  = @user. email
%p
  %b Password:
  = @user.password
%p
  %b Phone:
  = @user.phone
%p
  %b Full name:
  = @user.full_name
%p
  %b Birthday:
  = @user.birthday
%p
  %b Create date:
  = @user.create_date
= link_to 'Edit', edit_user_path(@user)
|
\#{link_to 'Back', users_path}