config/routes.rb
MyAssignment::Application.routes.draw do
  get "sessions/new"

  get "session/new"

  resources :book_categories

  get "store/index"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    post "logout" => :destroy
  end

  resources :carts

  resources :order_lines

  resources :orders

  resources :comments

  resources :categories

  resources :users
  devise_scope :user do
    controller "my_devise/my_passwords" do
      get "reset_password/reset_password_token/:reset_password_token", :to => :reset_password, :as => 'reset_password' 
      post "update_password", :to => :update_password
    end
  end
  devise_for :users, :controllers => {:passwords => "my_devise/my_passwords" }
  controller :users do 
    get "my_profile", :to => :edit_profile
    get "change_password", :to => :change_password
    get "change_email", :to => :change_email
  end

  controller :orders do 
    get "my_orders", :to => :my_orders
  end
  controller :carts do 
    get "check_session_alive", :to => :check_session_alive
  end

  
  get "category/:category/per/:per", :to => "store#index", :as => 'category_filter'
  post "order_lines/book/:book_id", :to => "order_lines#create", :as => 'add_to_cart'
  match "store/index?page=:id", :to => 'store#index', :as => 'store'
  get "store/per/:per", :to => 'store#index'

  root to: 'store#index', as: 'store' 
  resources :books

  match ':controller(/:action(/:id))(.:format)'
end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  attr_accessible :order_id, :book_id, :cart_id, :quantity, :unit_price

  belongs_to :order
  belongs_to :book
  belongs_to :cart

  def total_price
    book.price * quantity
  end

  class << self
    def update_order_lines(in_order_id,in_cart_id)
      order_lines = OrderLine.where('cart_id = ?', "#{in_cart_id}")
      order_lines.update_all(:order_id => in_order_id, :cart_id => nil)    
    end
  end
end

app/controllers/order_lines_controller.rb
class OrderLinesController < ApplicationController
  # GET /order_lines
  # GET /order_lines.json
  before_filter :admin_authorize, :only => [:edit, :update]
  def index
    @cart = current_cart
    @order_lines = OrderLine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @order_lines }
    end
  end

  # GET /order_lines/1
  # GET /order_lines/1.json
  def show
    @cart = current_cart
    @order_line = OrderLine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order_line }
    end
  end

  # GET /order_lines/new
  # GET /order_lines/new.json
  def new
    @cart = current_cart
    @order_line = OrderLine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order_line }
    end
  end

  # GET /order_lines/1/edit
  def edit
    @cart = current_cart
    @order_line = OrderLine.find(params[:id])
  end

  # POST /order_lines
  # POST /order_lines.json
  def create
    @cart = current_cart
    book = Book.find(params[:book_id])
    @order_line = @cart.add_book(book.id)
    
    respond_to do |format|
      if @order_line.save
        format.html { redirect_to store_url, notice: "The book #{book.title} has been added to cart" }
        format.js
        format.json { render json: @order_line, status: :created, location: @order_line }
      else
        format.html { render action: "new" }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /order_lines/1
  # PUT /order_lines/1.json
  def update
    @order_line = OrderLine.find(params[:id])

    respond_to do |format|
      if @order_line.update_attributes(params[:order_line])
        format.html { redirect_to @order_line, notice: 'Order line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_lines/1
  # DELETE /order_lines/1.json
  def destroy
    @cart = current_cart
    @order_line = @cart.minus_quantity(params[:id])


    respond_to do |format|
      if @order_line.save
        format.html { redirect_to order_lines_url, notice: "One order item has been deleted" }
        format.js
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/views/order_lines/_form.html.haml
= form_for(@order_line) do |f|
  - if @order_line.errors.any?
    #error_explanation
      %h2
        = pluralize(@order_line.errors.count, "error")
        prohibited this order_line from being saved:
      %ul
        - @order_line.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label : order_id
    %br/
    = f.number_field : order_id
  .field
    = f.label :book_id
    %br/
    = f.number_field :book_id
  .field
    = f.label :unit_price
    %br/
    = f.text_field :unit_price
  .field
    = f.label :quantity
    %br/
    = f.number_field :quantity
  .actions
    = f.submit

app/views/order_lines/_order_line.html.haml
%tr
  %td
    = order_line.quantity
    x
  %td= truncate order_line.book.title, :length => 7
  %td= number_to_currency(order_line.unit_price)
  %td= number_to_currency(order_line.total_price)
  %td= button_to "+", order_lines_path(book_id: order_line.book), method: :post, :remote => true
  %td= button_to "-", order_line_path(order_line.book_id), method: :delete, :remote => true

app/views/order_lines/create.js.erb
if($("#cart").is(":visible") == false){
	$("#cart").slideDown();
}

$('#cart').html("<%=j render @cart %>");

app/views/order_lines/create.js.haml
if($("#cart").is(":visible") == false){
$("#cart").slideDown();
$(function(){
setSessionTimeout('#{check_session_alive_path}', #{expire_time_left})
});
}
$('#cart').html('#{j render @cart}');

app/views/order_lines/destroy.js.erb
$("#cart").html("<%=j render @cart %>");
if($("#cart tr").length == 1 ){
	$("#cart").slideUp();
}

app/views/order_lines/edit.html.haml
%h1 Editing order_line
= render 'form'
= link_to 'Show', @order_line
|
\#{link_to 'Back', order_lines_path}

app/views/order_lines/index.html.haml
%h1 Listing order_lines
%table
  %tr
    %th order
    %th Book
    %th Unit price
    %th Quantity
    %th
    %th
    %th
  - @order_lines.each do |order_line|
    %tr
      %td= order_line.order_id
      %td= order_line.book_id
      %td= order_line.unit_price
      %td= order_line.quantity
      %td= link_to 'Show', order_line
      %td= link_to 'Edit', edit_order_line_path(order_line)
      %td= link_to 'Destroy', order_line, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Order line', new_order_line_path

app/views/order_lines/new.html.haml
%h1 New order_line
= render 'form'
= link_to 'Back', order_lines_path

app/views/order_lines/show.html.haml
%p#notice= notice
%p
  %b order:
  = @order_line. order_id
%p
  %b Book:
  = @order_line.book_id
%p
  %b Unit price:
  = @order_line.unit_price
%p
  %b Quantity:
  = @order_line.quantity
= link_to 'Edit', edit_order_line_path(@order_line)
|
\#{link_to 'Back', order_lines_path}