config/routes.rb
MyAssignment::Application.routes.draw do
  get "sessions/new"

  get "session/new"

  resources :book_categories

  get "store/index"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    post "logout" => :destroy
  end

  resources :carts

  resources :order_lines

  resources :orders

  resources :comments

  resources :categories

  resources :users
  devise_scope :user do
    controller "my_devise/my_passwords" do
      get "reset_password/reset_password_token/:reset_password_token", :to => :reset_password, :as => 'reset_password' 
      post "update_password", :to => :update_password
    end
  end
  devise_for :users, :controllers => {:passwords => "my_devise/my_passwords" }
  controller :users do 
    get "my_profile", :to => :edit_profile
    get "change_password", :to => :change_password
    get "change_email", :to => :change_email
  end

  controller :orders do 
    get "my_orders", :to => :my_orders
  end
  controller :carts do 
    get "check_session_alive", :to => :check_session_alive
  end

  
  get "category/:category/per/:per", :to => "store#index", :as => 'category_filter'
  post "order_lines/book/:book_id", :to => "order_lines#create", :as => 'add_to_cart'
  match "store/index?page=:id", :to => 'store#index', :as => 'store'
  get "store/per/:per", :to => 'store#index'

  root to: 'store#index', as: 'store' 
  resources :books

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MyAssignment
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body{:id => controller.controller_name}
    .row
      .col-md-3
        .sidebar-nav{:style => "position: fixed"}
          .well{:style => "width:300px; padding: 8px 0;"}
            %ul.nav.nav-list
              - if current_user
                / Logged in user
                %li.nav-header
                  %strong
                    Welcome, #{current_user.username}
                %li= link_to "My Profile", my_profile_path
                %li= link_to "My Orders", my_orders_path
                %li= link_to "Logout", logout_path, :method => "post", :id => 'logout'
              - else
                / Anonymous user
                %li.nav-header
                  %strong Welcome
                %li= link_to "Login", login_path
                %li= link_to "Register", new_user_path
                %li= link_to "Forgot password?", new_user_password_path
              %li= link_to "Home", store_path
            #admin_pane
              - if current_user && current_user.admin?
                %ul.nav.nav_list
                  %li.nav_header
                    %strong Admin Panel
                  %li= link_to "Users", users_path
                  %li= link_to "Books", books_path
                  %li= link_to "Categories", categories_path
                  %li= link_to "Orders", orders_path
                  %li= link_to "OrderLines", order_lines_path
            #cart
              - if @cart.order_lines.count > 0
                = render 'carts/cart', :object => @cart
          - if notice
            .alert.alert-success= notice
          - if alert
            .alert.alert-danger= alert
      #main-content.col-md-9
        = yield
    -if expire_time_left
      :javascript
        $(function(){
          setSessionTimeout('#{check_session_alive_path}', #{expire_time_left})
        });